In [5]:
import pandas as pd

In [3]:
data_path = "/Users/yeeunpark/Desktop/23-2/Machine Learning/"

In [6]:
training_label = pd.read_csv(data_path+"128.치매 고위험군 라이프로그/01.데이터/1.Training/라벨링데이터/1.걸음걸이/training_label.csv")
training_label

         SAMPLE_EMAIL DIAG_NM
0    nia+315@rowan.kr      CN
1    nia+014@rowan.kr     MCI
2    nia+220@rowan.kr      CN
3    nia+096@rowan.kr     MCI
4    nia+396@rowan.kr      CN
..                ...     ...
136  nia+181@rowan.kr      CN
137  nia+354@rowan.kr      CN
138  nia+448@rowan.kr     MCI
139  nia+394@rowan.kr      CN
140  nia+067@rowan.kr     Dem

[141 rows x 2 columns]

In [8]:
val_label = pd.read_csv(data_path+"128.치매 고위험군 라이프로그/01.데이터/2.Validation/라벨링데이터/1.걸음걸이/val_label.csv")
val_label

        SAMPLE_EMAIL DIAG_NM
0   nia+163@rowan.kr      CN
1   nia+280@rowan.kr      CN
2   nia+322@rowan.kr      CN
3   nia+173@rowan.kr      CN
4   nia+320@rowan.kr      CN
5   nia+263@rowan.kr      CN
6   nia+027@rowan.kr      CN
7   nia+424@rowan.kr      CN
8   nia+266@rowan.kr      CN
9   nia+245@rowan.kr     MCI
10  nia+064@rowan.kr      CN
11  nia+380@rowan.kr      CN
12   nia+85@rowan.kr      CN
13  nia+404@rowan.kr      CN
14  nia+374@rowan.kr      CN
15  nia+323@rowan.kr      CN
16  nia+100@rowan.kr      CN
17  nia+269@rowan.kr      CN
18  nia+112@rowan.kr     Dem
19  nia+327@rowan.kr      CN
20  nia+128@rowan.kr     MCI
21  nia+377@rowan.kr      CN
22  nia+045@rowan.kr     Dem
23  nia+192@rowan.kr      CN
24  nia+084@rowan.kr      CN
25  nia+406@rowan.kr      CN
26  nia+210@rowan.kr      CN
27  nia+223@rowan.kr      CN
28  nia+311@rowan.kr      CN
29  nia+022@rowan.kr     MCI
30  nia+013@rowan.kr     MCI
31  nia+450@rowan.kr      CN
32  nia+287@rowan.kr     Dem

In [9]:
train_activity = pd.read_csv(data_path+"128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/1.걸음걸이/train_activity.csv")
train_activity

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total,CONVERT(activity_class_5min USING utf8),CONVERT(activity_met_1min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,...,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,...,78,100,100,54,100,97,4212,207,1/1/2/2/2/2/1/1/1/1/1/1/1/2/2/2/2/2/2/3/3/2/2/...,1.2/0.9/1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/...
1,nia+279@rowan.kr,1.25000,145,2159,...,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,...,60,100,100,58,96,96,3306,140,1/1/1/2/2/2/2/2/2/2/2/2/1/1/1/1/1/2/3/3/3/3/2/...,0.9/0.9/1.3/1/0.9/0.9/1.1/0.9/1/0.9/1/0.9/1/0....
2,nia+279@rowan.kr,1.21875,118,2140,...,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,...,43,95,100,55,71,83,2550,131,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
3,nia+279@rowan.kr,1.28125,180,2240,...,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,...,43,100,100,58,71,59,4009,208,1/1/1/1/1/1/1/1/1/1/2/2/2/2/3/3/3/2/3/3/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
4,nia+279@rowan.kr,1.46875,374,2559,...,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,...,43,100,100,89,40,46,8081,517,1/1/1/2/2/2/2/2/2/1/1/1/3/2/2/1/2/2/2/3/3/2/2/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,...,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,...,25,43,100,45,40,95,4972,190,1/1/1/1/1/1/1/1/1/1/2/3/2/2/2/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
9701,nia+206@rowan.kr,1.53125,570,2682,...,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,...,43,95,100,76,71,93,11878,394,1/1/1/1/1/1/2/2/2/2/2/2/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/1.1/0.9/0.9/1.1/0.9/0.9/0.9/0....
9702,nia+206@rowan.kr,1.34375,295,2331,...,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,...,25,100,100,70,40,95,5752,207,1/1/1/2/3/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,1.1/0.9/0.9/0.9/1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/...
9703,nia+206@rowan.kr,1.31250,186,2280,...,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,...,25,95,100,47,40,93,3852,156,1/1/1/1/1/1/1/1/1/1/1/1/2/2/0/0/0/0/0/0/0/0/0/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
9704,nia+206@rowan.kr,1.37500,83,1891,...,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,...,25,100,100,48,40,82,1500,68,1/1/1/1/2/2/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....

In [10]:
val_activity = pd.read_csv(data_path+"128.치매 고위험군 라이프로그/01.데이터/2.Validation/원천데이터/1.걸음걸이/val_activity.csv")
val_activity

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total,CONVERT(activity_class_5min USING utf8),CONVERT(activity_met_1min USING utf8)
0,nia+404@rowan.kr,1.71875,730,2944,...,14346,2020-11-28T03:59:59+09:00,2020-11-27T04:00:00+09:00,0,417,...,95,100,100,86,100,98,15867,592,2/1/1/1/1/1/2/2/1/1/1/1/1/1/2/2/2/3/2/2/2/2/2/...,0.9/0.9/1.4/1.9/1.1/0.9/0.9/1.1/1.3/1/0.9/1.1/...
1,nia+404@rowan.kr,1.40625,342,2449,...,6352,2020-11-29T03:59:59+09:00,2020-11-28T04:00:00+09:00,0,473,...,78,100,100,83,100,97,7755,400,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/2/2/2/2/2/...,1.2/1.1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
2,nia+404@rowan.kr,1.46875,401,2544,...,7297,2020-11-30T03:59:59+09:00,2020-11-29T04:00:00+09:00,0,586,...,95,100,100,71,96,96,8341,386,1/1/1/1/1/1/1/2/1/1/1/1/2/2/2/2/2/1/1/1/1/1/2/...,1.1/1.1/1.2/1.1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
3,nia+404@rowan.kr,0.34375,27,1850,...,491,2020-12-01T03:59:59+09:00,2020-11-30T04:00:00+09:00,0,176,...,95,100,100,74,96,92,8122,35,2/1/2/2/1/2/1/1/2/1/1/1/1/1/2/1/1/1/1/1/2/2/2/...,0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/...
4,nia+404@rowan.kr,1.46875,333,2518,...,5861,2020-12-02T03:59:59+09:00,2020-12-01T04:00:00+09:00,0,646,...,95,100,100,65,71,80,7378,383,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/2/3/3/2/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1.59375,648,2760,...,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,...,100,100,95,88,100,100,14654,447,1/2/1/1/1/2/2/3/3/2/5/3/2/2/2/2/2/1/2/1/1/1/1/...,1.2/0.9/0.9/0.9/1.1/1.1/0.9/1.1/2.4/0.9/0.9/0....
2474,nia+280@rowan.kr,1.43750,379,2507,...,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,...,100,100,89,65,100,99,8425,374,1/1/1/1/1/2/2/2/3/3/4/2/2/2/2/1/2/2/1/1/1/2/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
2475,nia+280@rowan.kr,1.56250,670,2747,...,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,...,100,100,100,95,100,99,15341,442,3/3/3/3/3/2/3/3/2/2/2/2/2/2/2/2/2/2/2/2/1/2/1/...,2.1/1.9/2.2/2.4/2.8/2.2/1.9/1.7/1.9/1.4/2.6/1....
2476,nia+280@rowan.kr,1.46875,556,2570,...,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,...,100,78,95,87,100,100,12006,312,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
2477,nia+280@rowan.kr,1.34375,311,2341,...,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,...,100,100,89,67,100,99,6691,294,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,1.3/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....

In [11]:
train_sleep = pd.read_csv(data_path+"128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/2.수면/train_sleep.csv")
train_sleep

,EMAIL,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,8700,2020-10-19T05:10:28+09:00,2020-10-18T18:38:28+09:00,17.875,10110,37920,77,...,53.04,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,6570,2020-10-20T05:37:52+09:00,2020-10-19T21:39:52+09:00,18.000,7440,28680,77,...,52.82,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,10530,2020-10-21T05:45:28+09:00,2020-10-20T20:51:28+09:00,18.000,4620,32040,67,...,52.01,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,4080,2020-10-22T05:12:16+09:00,2020-10-21T22:08:16+09:00,17.500,7440,25440,84,...,51.07,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,7170,2020-10-23T02:23:30+09:00,2020-10-22T20:38:30+09:00,17.875,4320,20700,65,...,50.80,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,6000,2020-12-24T06:51:37+09:00,2020-12-23T21:35:37+09:00,15.875,1710,33360,82,...,63.75,...,76,81,95,86,-0.09,-0.09,27360,68/66/67/67/68/69/69/70/71/71/71/69/72/70/70/7...,4/4/2/2/2/1/1/1/1/1/1/2/2/3/3/2/2/2/2/2/3/4/2/...,26/16/19/18/16/18/19/17/15/16/15/13/11/13/13/1...
9701,nia+206@rowan.kr,5700,2020-12-26T06:36:19+09:00,2020-12-25T22:54:19+09:00,16.125,0,27720,79,...,67.40,...,69,86,89,64,0.41,0.41,22020,0/0/65/65/66/67/69/72/73/72/73/74/73/74/75/75/...,4/4/2/2/2/2/2/2/2/2/2/2/4/4/4/4/2/3/3/3/2/2/4/...,0/0/13/12/12/13/12/12/12/16/13/12/13/17/13/18/...
9702,nia+206@rowan.kr,5070,2020-12-27T07:56:40+09:00,2020-12-26T22:05:40+09:00,15.625,480,35460,86,...,64.84,...,86,89,98,97,0.27,0.27,30390,0/0/0/64/64/64/64/65/65/66/66/66/66/68/68/68/6...,4/4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/2/4/4/2/2/2/...,0/0/0/14/17/18/14/14/17/15/17/12/17/12/13/12/1...
9703,nia+206@rowan.kr,2040,2020-12-28T05:05:45+09:00,2020-12-27T21:21:45+09:00,15.875,2220,27840,93,...,67.05,...,98,89,86,80,-0.05,-0.05,25800,0/60/60/61/60/60/60/62/64/64/64/64/65/68/70/70...,4/4/1/2/2/2/2/1/2/2/2/1/1/1/3/3/1/1/2/2/3/3/3/...,0/14/15/14/15/16/17/16/16/18/18/20/23/15/21/20...
9704,nia+206@rowan.kr,3390,2020-12-29T06:10:26+09:00,2020-12-28T22:59:26+09:00,16.625,600,25860,87,...,62.49,...,88,99,76,66,0.26,0.26,22470,0/0/0/62/62/62/61/60/60/61/61/62/0/67/66/66/66...,4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/3/2/2/2/2/2/2/...,0/0/0/19/18/22/20/16/16/16/14/18/0/36/28/23/21...

In [12]:
val_sleep = pd.read_csv(data_path+"128.치매 고위험군 라이프로그/01.데이터/2.Validation/원천데이터/2.수면/val_sleep.csv")
val_sleep

,EMAIL,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+404@rowan.kr,13950,2020-11-27T06:54:33+09:00,2020-11-26T21:03:33+09:00,16.500,2100,35460,61,...,70.53,...,27,97,66,62,-0.12,-0.12,21510,0/73/73/73/72/71/70/71/71/71/70/70/73/72/74/74...,4/2/4/3/3/1/2/2/2/2/2/2/3/3/3/4/4/3/2/2/2/2/2/...,0/10/10/10/11/11/10/12/18/13/14/12/10/10/18/17...
1,nia+404@rowan.kr,7680,2020-11-28T06:35:25+09:00,2020-11-27T23:43:25+09:00,17.375,2430,24720,69,...,68.01,...,46,91,35,44,-0.32,-0.32,17040,69/70/69/69/70/72/71/72/70/69/69/69/68/68/63/6...,2/4/2/2/2/2/3/1/2/2/4/4/2/2/2/2/2/2/2/2/2/2/4/...,23/23/26/24/18/13/15/14/17/20/24/30/23/25/22/1...
2,nia+404@rowan.kr,11880,2020-11-29T05:53:39+09:00,2020-11-28T20:39:39+09:00,17.000,2820,33240,64,...,64.89,...,34,89,41,62,0.07,0.07,21360,0/74/73/73/74/74/74/71/71/70/70/69/70/68/66/69...,4/2/4/4/1/1/1/4/4/4/4/4/4/4/2/3/4/2/2/4/2/2/2/...,0/11/14/20/13/14/14/16/27/29/27/20/19/19/14/12...
3,nia+404@rowan.kr,9600,2020-11-30T05:53:11+09:00,2020-11-29T21:38:11+09:00,17.250,1770,29700,68,...,63.70,...,44,86,29,56,-0.41,-0.41,20100,73/70/71/72/75/75/73/70/70/70/67/63/63/63/63/6...,4/4/4/4/3/3/3/2/4/4/4/2/2/2/2/2/2/2/2/4/2/2/2/...,24/28/19/17/12/10/17/20/23/23/25/31/26/25/34/3...
4,nia+404@rowan.kr,10710,2020-12-01T05:37:37+09:00,2020-11-30T20:53:37+09:00,17.250,3150,31440,66,...,67.07,...,39,14,54,59,-0.27,-0.27,20730,0/0/0/0/0/0/0/0/69/69/71/69/65/66/64/64/65/66/...,4/4/4/4/4/4/4/4/4/4/4/2/2/2/2/3/3/2/4/4/4/2/2/...,0/0/0/0/0/0/0/0/21/22/26/23/19/29/22/17/14/13/...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2473,nia+280@rowan.kr,1680,2021-02-12T04:04:11+09:00,2021-02-12T00:11:11+09:00,18.500,6030,13980,88,...,63.33,...,90,89,22,25,-0.27,-0.27,12300,66/66/65/64/65/65/65/63/63/63/62/65/64/60/60/6...,4/2/4/4/2/2/2/2/3/2/1/1/2/2/1/1/1/1/1/1/3/2/2/...,45/35/29/27/34/30/31/32/41/40/37/28/43/46/53/4...
2474,nia+280@rowan.kr,12840,2021-02-13T09:20:01+09:00,2021-02-12T21:46:01+09:00,18.000,4020,41640,69,...,60.22,...,46,97,95,92,-0.13,-0.13,28800,66/0/0/69/69/69/67/65/63/63/64/64/66/70/66/65/...,4/2/4/2/1/4/2/2/2/1/1/1/1/4/2/2/2/2/3/3/3/3/3/...,21/0/0/30/31/35/35/29/37/34/35/35/31/15/20/23/...
2475,nia+280@rowan.kr,11250,2021-02-15T08:18:10+09:00,2021-02-14T21:40:10+09:00,18.375,6060,38280,71,...,65.38,...,51,81,62,85,0.21,0.21,27030,63/63/63/62/63/62/62/62/63/69/71/68/70/0/0/72/...,4/2/2/2/2/2/1/1/1/1/2/2/4/4/4/1/2/3/3/3/2/2/2/...,29/28/28/32/27/35/34/36/31/27/14/29/16/0/0/19/...
2476,nia+280@rowan.kr,7410,2021-02-16T07:43:02+09:00,2021-02-15T19:41:02+09:00,18.000,7110,43320,83,...,62.43,...,79,75,98,100,0.69,0.69,35910,0/72/71/70/68/69/69/68/68/0/0/0/68/68/68/68/67...,4/2/2/4/4/2/1/1/4/4/4/4/1/1/1/1/2/2/2/4/2/1/1/...,0/19/14/14/22/20/22/22/22/0/0/0/31/30/34/30/26...
2477,nia+280@rowan.kr,3360,2021-02-17T06:02:59+09:00,2021-02-16T22:21:59+09:00,18.500,4230,27660,88,...,64.71,...,90,86,23,74,-0.91,-0.91,24300,0/0/0/0/64/66/66/65/65/67/68/66/66/66/66/66/67...,4/4/4/4/2/2/2/1/1/1/1/2/2/2/1/1/2/3/2/2/2/2/2/...,0/0/0/0/25/31/33/35/36/33/17/30/30/29/31/29/23...

In [13]:
label_data = pd.concat([training_label, val_label])
label_data.reset_index(drop='index', inplace=True)
label_data

         SAMPLE_EMAIL DIAG_NM
0    nia+315@rowan.kr      CN
1    nia+014@rowan.kr     MCI
2    nia+220@rowan.kr      CN
3    nia+096@rowan.kr     MCI
4    nia+396@rowan.kr      CN
..                ...     ...
169  nia+311@rowan.kr      CN
170  nia+022@rowan.kr     MCI
171  nia+013@rowan.kr     MCI
172  nia+450@rowan.kr      CN
173  nia+287@rowan.kr     Dem

[174 rows x 2 columns]

In [14]:
activity_data = pd.concat([train_activity, val_activity])
activity_data.reset_index(drop='index', inplace=True)
activity_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total,CONVERT(activity_class_5min USING utf8),CONVERT(activity_met_1min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,...,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,...,78,100,100,54,100,97,4212,207,1/1/2/2/2/2/1/1/1/1/1/1/1/2/2/2/2/2/2/3/3/2/2/...,1.2/0.9/1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/...
1,nia+279@rowan.kr,1.25000,145,2159,...,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,...,60,100,100,58,96,96,3306,140,1/1/1/2/2/2/2/2/2/2/2/2/1/1/1/1/1/2/3/3/3/3/2/...,0.9/0.9/1.3/1/0.9/0.9/1.1/0.9/1/0.9/1/0.9/1/0....
2,nia+279@rowan.kr,1.21875,118,2140,...,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,...,43,95,100,55,71,83,2550,131,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
3,nia+279@rowan.kr,1.28125,180,2240,...,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,...,43,100,100,58,71,59,4009,208,1/1/1/1/1/1/1/1/1/1/2/2/2/2/3/3/3/2/3/3/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
4,nia+279@rowan.kr,1.46875,374,2559,...,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,...,43,100,100,89,40,46,8081,517,1/1/1/2/2/2/2/2/2/1/1/1/3/2/2/1/2/2/2/3/3/2/2/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12178,nia+280@rowan.kr,1.59375,648,2760,...,12256,2021-02-13T03:59:59+09:00,2021-02-12T04:00:00+09:00,0,444,...,100,100,95,88,100,100,14654,447,1/2/1/1/1/2/2/3/3/2/5/3/2/2/2/2/2/1/2/1/1/1/1/...,1.2/0.9/0.9/0.9/1.1/1.1/0.9/1.1/2.4/0.9/0.9/0....
12179,nia+280@rowan.kr,1.43750,379,2507,...,6973,2021-02-14T03:59:59+09:00,2021-02-13T04:00:00+09:00,0,623,...,100,100,89,65,100,99,8425,374,1/1/1/1/1/2/2/2/3/3/4/2/2/2/2/1/2/2/1/1/1/2/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
12180,nia+280@rowan.kr,1.56250,670,2747,...,13008,2021-02-16T03:59:59+09:00,2021-02-15T04:00:00+09:00,0,422,...,100,100,100,95,100,99,15341,442,3/3/3/3/3/2/3/3/2/2/2/2/2/2/2/2/2/2/2/2/1/2/1/...,2.1/1.9/2.2/2.4/2.8/2.2/1.9/1.7/1.9/1.4/2.6/1....
12181,nia+280@rowan.kr,1.46875,556,2570,...,11043,2021-02-17T03:59:59+09:00,2021-02-16T04:00:00+09:00,0,452,...,100,78,95,87,100,100,12006,312,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
12182,nia+280@rowan.kr,1.34375,311,2341,...,5943,2021-02-18T03:59:59+09:00,2021-02-17T04:00:00+09:00,0,595,...,100,100,89,67,100,99,6691,294,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,1.3/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....

In [15]:
sleep_data = pd.concat([train_sleep, val_sleep])
sleep_data.reset_index(drop='index', inplace=True)
sleep_data

,EMAIL,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,8700,2020-10-19T05:10:28+09:00,2020-10-18T18:38:28+09:00,17.875,10110,37920,77,...,53.04,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,6570,2020-10-20T05:37:52+09:00,2020-10-19T21:39:52+09:00,18.000,7440,28680,77,...,52.82,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,10530,2020-10-21T05:45:28+09:00,2020-10-20T20:51:28+09:00,18.000,4620,32040,67,...,52.01,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,4080,2020-10-22T05:12:16+09:00,2020-10-21T22:08:16+09:00,17.500,7440,25440,84,...,51.07,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,7170,2020-10-23T02:23:30+09:00,2020-10-22T20:38:30+09:00,17.875,4320,20700,65,...,50.80,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12178,nia+280@rowan.kr,1680,2021-02-12T04:04:11+09:00,2021-02-12T00:11:11+09:00,18.500,6030,13980,88,...,63.33,...,90,89,22,25,-0.27,-0.27,12300,66/66/65/64/65/65/65/63/63/63/62/65/64/60/60/6...,4/2/4/4/2/2/2/2/3/2/1/1/2/2/1/1/1/1/1/1/3/2/2/...,45/35/29/27/34/30/31/32/41/40/37/28/43/46/53/4...
12179,nia+280@rowan.kr,12840,2021-02-13T09:20:01+09:00,2021-02-12T21:46:01+09:00,18.000,4020,41640,69,...,60.22,...,46,97,95,92,-0.13,-0.13,28800,66/0/0/69/69/69/67/65/63/63/64/64/66/70/66/65/...,4/2/4/2/1/4/2/2/2/1/1/1/1/4/2/2/2/2/3/3/3/3/3/...,21/0/0/30/31/35/35/29/37/34/35/35/31/15/20/23/...
12180,nia+280@rowan.kr,11250,2021-02-15T08:18:10+09:00,2021-02-14T21:40:10+09:00,18.375,6060,38280,71,...,65.38,...,51,81,62,85,0.21,0.21,27030,63/63/63/62/63/62/62/62/63/69/71/68/70/0/0/72/...,4/2/2/2/2/2/1/1/1/1/2/2/4/4/4/1/2/3/3/3/2/2/2/...,29/28/28/32/27/35/34/36/31/27/14/29/16/0/0/19/...
12181,nia+280@rowan.kr,7410,2021-02-16T07:43:02+09:00,2021-02-15T19:41:02+09:00,18.000,7110,43320,83,...,62.43,...,79,75,98,100,0.69,0.69,35910,0/72/71/70/68/69/69/68/68/0/0/0/68/68/68/68/67...,4/2/2/4/4/2/1/1/4/4/4/4/1/1/1/1/2/2/2/4/2/1/1/...,0/19/14/14/22/20/22/22/22/0/0/0/31/30/34/30/26...
12182,nia+280@rowan.kr,3360,2021-02-17T06:02:59+09:00,2021-02-16T22:21:59+09:00,18.500,4230,27660,88,...,64.71,...,90,86,23,74,-0.91,-0.91,24300,0/0/0/0/64/66/66/65/65/67/68/66/66/66/66/66/67...,4/4/4/4/2/2/2/1/1/1/1/2/2/2/1/1/2/3/2/2/2/2/2/...,0/0/0/0/25/31/33/35/36/33/17/30/30/29/31/29/23...

In [16]:
len(val_sleep.EMAIL.unique())

33

In [17]:
activity_data.drop(columns=['activity_class_5min','activity_day_end','activity_day_start','activity_met_1min','CONVERT(activity_class_5min USING utf8)','CONVERT(activity_met_1min USING utf8)'], inplace=True)
activity_data

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_high,activity_inactive,activity_inactivity_alerts,activity_low,activity_medium,...,activity_rest,activity_score,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total
0,nia+279@rowan.kr,1.28125,196,2251,3353,0,714,0,201,6,...,519,87,78,100,100,54,100,97,4212,207
1,nia+279@rowan.kr,1.25000,145,2159,2516,0,719,0,131,9,...,464,83,60,100,100,58,96,96,3306,140
2,nia+279@rowan.kr,1.21875,118,2140,1716,0,708,1,125,6,...,601,73,43,95,100,55,71,83,2550,131
3,nia+279@rowan.kr,1.28125,180,2240,2791,0,705,0,203,5,...,442,70,43,100,100,58,71,59,4009,208
4,nia+279@rowan.kr,1.46875,374,2559,5393,0,437,0,511,6,...,453,70,43,100,100,89,40,46,8081,517
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12178,nia+280@rowan.kr,1.59375,648,2760,12256,0,444,0,381,66,...,549,97,100,100,95,88,100,100,14654,447
12179,nia+280@rowan.kr,1.43750,379,2507,6973,0,623,0,361,13,...,443,91,100,100,89,65,100,99,8425,374
12180,nia+280@rowan.kr,1.56250,670,2747,13008,0,422,0,366,76,...,576,99,100,100,100,95,100,99,15341,442
12181,nia+280@rowan.kr,1.46875,556,2570,11043,0,452,2,244,68,...,676,95,100,78,95,87,100,100,12006,312
12182,nia+280@rowan.kr,1.34375,311,2341,5943,0,595,0,277,17,...,551,91,100,100,89,67,100,99,6691,294

In [18]:
sleep_data.drop(columns=['sleep_hr_5min','sleep_bedtime_end','sleep_bedtime_start','sleep_hypnogram_5min','sleep_rmssd_5min','CONVERT(sleep_hr_5min USING utf8)','CONVERT(sleep_hypnogram_5min USING utf8)','CONVERT(sleep_rmssd_5min USING utf8)'], inplace=True)
sleep_data

,EMAIL,sleep_awake,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_average,sleep_hr_lowest,sleep_is_longest,sleep_light,...,sleep_score_alignment,sleep_score_deep,sleep_score_disturbances,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total
0,nia+279@rowan.kr,8700,17.875,10110,37920,77,53.04,49,1,15330,...,87,100,78,65,89,56,94,0.00,0.00,29220
1,nia+279@rowan.kr,6570,18.000,7440,28680,77,52.82,49,1,11820,...,100,98,77,65,97,43,65,0.34,0.34,22110
2,nia+279@rowan.kr,10530,18.000,4620,32040,67,52.01,47,1,12360,...,100,94,60,41,75,68,62,-0.07,-0.07,21510
3,nia+279@rowan.kr,4080,17.500,7440,25440,84,51.07,46,1,9060,...,100,98,80,81,83,73,62,-0.14,-0.14,21360
4,nia+279@rowan.kr,7170,17.875,4320,20700,65,50.80,47,1,7470,...,80,88,72,39,78,25,29,-0.50,-0.50,13530
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12178,nia+280@rowan.kr,1680,18.500,6030,13980,88,63.33,60,1,4800,...,100,97,90,90,89,22,25,-0.27,-0.27,12300
12179,nia+280@rowan.kr,12840,18.000,4020,41640,69,60.22,53,1,18270,...,100,81,75,46,97,95,92,-0.13,-0.13,28800
12180,nia+280@rowan.kr,11250,18.375,6060,38280,71,65.38,59,1,16830,...,100,97,56,51,81,62,85,0.21,0.21,27030
12181,nia+280@rowan.kr,7410,18.000,7110,43320,83,62.43,55,1,21150,...,100,98,71,79,75,98,100,0.69,0.69,35910
12182,nia+280@rowan.kr,3360,18.500,4230,27660,88,64.71,59,1,18480,...,100,86,58,90,86,23,74,-0.91,-0.91,24300

In [19]:
activity_mean = activity_data.groupby("EMAIL").mean()
activity_mean

,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_high,activity_inactive,activity_inactivity_alerts,activity_low,activity_medium,activity_met_min_high,...,activity_rest,activity_score,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total
EMAIL,,,,,,,,,,,,,,,,,,,,,
nia+003@rowan.kr,1.262897,202.571429,2208.333333,3659.730159,0.793651,615.142857,0.809524,146.428571,18.333333,5.984127,...,618.063492,58.682540,18.793651,92.492063,99.698413,66.269841,21.682540,53.031746,4518.460317,165.555556
nia+005@rowan.kr,1.370299,217.477876,1773.504425,5084.876106,0.256637,574.619469,0.539823,281.300885,15.398230,1.778761,...,521.247788,54.522124,11.601770,95.566372,96.203540,72.088496,6.371681,46.530973,6431.831858,296.955752
nia+010@rowan.kr,1.390625,259.672414,2365.137931,3877.741379,0.637931,632.482759,0.362069,328.827586,9.068966,4.379310,...,434.086207,65.758621,54.068966,97.155172,99.862069,64.965517,16.982759,41.637931,5868.758621,338.534483
nia+013@rowan.kr,1.478484,493.147541,2577.590164,8769.811475,0.836066,481.016393,0.745902,314.918033,48.426230,5.901639,...,556.114754,91.590164,89.696721,93.565574,92.926230,81.926230,99.368852,98.139344,10764.614754,364.180328
nia+014@rowan.kr,1.442555,401.382353,2503.882353,7250.514706,0.382353,534.470588,0.176471,343.852941,30.970588,3.382353,...,492.205882,91.264706,92.147059,99.117647,98.235294,76.750000,83.750000,93.058824,9444.338235,375.205882
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nia+456@rowan.kr,1.542480,573.781250,2676.125000,10846.750000,5.421875,610.515625,0.609375,283.140625,64.000000,40.562500,...,433.781250,87.359375,96.984375,95.437500,76.703125,67.078125,100.000000,99.453125,11940.390625,352.562500
nia+458@rowan.kr,1.257353,200.549020,2206.941176,3377.098039,0.588235,507.117647,0.392157,206.823529,9.176471,4.333333,...,667.764706,61.686275,23.215686,97.568627,99.019608,77.529412,18.705882,53.647059,4347.235294,216.588235
nia+462@rowan.kr,1.595274,654.780488,2748.975610,12247.487805,3.121951,473.658537,0.560976,309.951220,84.804878,22.536585,...,520.682927,82.487805,94.756098,95.707317,50.731707,82.170732,99.902439,99.634146,13707.756098,397.878049
nia+475@rowan.kr,1.397418,311.869565,2410.043478,5543.195652,0.108696,675.282609,1.130435,278.891304,23.347826,0.782609,...,439.282609,80.434783,78.239130,88.760870,98.043478,58.978261,71.456522,77.326087,7436.413043,302.347826
nia+85@rowan.kr,1.336538,290.494505,2327.934066,5319.571429,0.274725,551.516484,0.538462,228.934066,24.351648,1.989011,...,551.065934,79.450549,66.681319,96.098901,98.087912,74.241758,61.307692,76.956044,6808.098901,253.560440

In [20]:
sleep_mean = sleep_data.groupby("EMAIL").mean()
sleep_mean

,sleep_awake,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_average,sleep_hr_lowest,sleep_is_longest,sleep_light,sleep_midpoint_at_delta,...,sleep_score_alignment,sleep_score_deep,sleep_score_disturbances,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total
EMAIL,,,,,,,,,,,,,,,,,,,,,
nia+003@rowan.kr,7162.857143,16.454365,4302.857143,30706.666667,77.126984,57.957937,52.158730,1.0,15489.047619,14927.746032,...,74.809524,75.492063,57.634921,65.253968,78.650794,54.904762,69.730159,0.022222,0.022222,23543.809524
nia+005@rowan.kr,2055.663717,16.307522,6152.123894,30115.752212,93.070796,65.231947,57.831858,1.0,16303.539823,11296.017699,...,86.849558,89.345133,83.601770,97.663717,83.973451,74.433628,81.097345,0.057434,0.057434,28060.088496
nia+010@rowan.kr,7252.241379,16.892241,3081.724138,27499.655172,74.068966,53.175345,46.982759,1.0,12873.103448,5635.620690,...,97.931034,61.517241,63.758621,58.034483,76.965517,64.672414,58.344828,-0.045862,-0.045862,20247.413793
nia+013@rowan.kr,3436.475410,17.292008,7519.180328,26599.672131,87.245902,51.671639,47.950820,1.0,13198.524590,11396.229508,...,90.139344,97.606557,72.549180,88.073770,81.721311,36.295082,69.049180,0.008033,0.008033,23163.196721
nia+014@rowan.kr,6641.911765,14.869485,4346.911765,28521.176471,77.764706,63.373676,56.720588,1.0,14918.382353,10957.205882,...,94.764706,76.867647,55.500000,66.970588,82.500000,38.779412,63.573529,-0.129706,-0.129706,21879.264706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nia+456@rowan.kr,9675.937500,17.121094,5021.718750,28637.812500,66.828125,66.115469,60.468750,1.0,11829.375000,12528.156250,...,88.718750,85.031250,57.468750,42.156250,83.828125,31.234375,51.750000,-0.125469,-0.125469,18961.875000
nia+458@rowan.kr,8269.411765,16.306373,6042.352941,36348.235294,78.156863,67.042157,60.705882,1.0,16081.176471,23158.392157,...,90.686275,88.882353,72.745098,67.705882,75.529412,82.607843,85.274510,-0.040000,-0.040000,28078.823529
nia+462@rowan.kr,7464.146341,16.292683,9676.829268,30509.268293,76.195122,59.360244,51.121951,1.0,11397.804878,33183.878049,...,90.073171,99.634146,71.121951,63.146341,85.317073,28.951220,68.634146,-0.037317,-0.037317,23045.121951
nia+475@rowan.kr,3759.782609,15.668478,6759.130435,23512.173913,83.739130,55.763478,51.717391,1.0,11130.000000,15638.304348,...,57.130435,94.456522,68.130435,80.413043,85.913043,27.586957,54.695652,-0.159348,-0.159348,19752.391304
nia+85@rowan.kr,5105.934066,18.589286,7260.329670,26963.076923,83.098901,64.131868,58.879121,1.0,12088.681319,11634.098901,...,87.626374,95.340659,76.604396,78.186813,82.230769,37.230769,63.285714,-0.008681,-0.008681,21857.142857

In [21]:
activity_sleep = pd.merge(activity_mean,sleep_mean, how='outer',on='EMAIL')
activity_sleep

,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_high,activity_inactive,activity_inactivity_alerts,activity_low,activity_medium,activity_met_min_high,...,sleep_score_alignment,sleep_score_deep,sleep_score_disturbances,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total
EMAIL,,,,,,,,,,,,,,,,,,,,,
nia+003@rowan.kr,1.262897,202.571429,2208.333333,3659.730159,0.793651,615.142857,0.809524,146.428571,18.333333,5.984127,...,74.809524,75.492063,57.634921,65.253968,78.650794,54.904762,69.730159,0.022222,0.022222,23543.809524
nia+005@rowan.kr,1.370299,217.477876,1773.504425,5084.876106,0.256637,574.619469,0.539823,281.300885,15.398230,1.778761,...,86.849558,89.345133,83.601770,97.663717,83.973451,74.433628,81.097345,0.057434,0.057434,28060.088496
nia+010@rowan.kr,1.390625,259.672414,2365.137931,3877.741379,0.637931,632.482759,0.362069,328.827586,9.068966,4.379310,...,97.931034,61.517241,63.758621,58.034483,76.965517,64.672414,58.344828,-0.045862,-0.045862,20247.413793
nia+013@rowan.kr,1.478484,493.147541,2577.590164,8769.811475,0.836066,481.016393,0.745902,314.918033,48.426230,5.901639,...,90.139344,97.606557,72.549180,88.073770,81.721311,36.295082,69.049180,0.008033,0.008033,23163.196721
nia+014@rowan.kr,1.442555,401.382353,2503.882353,7250.514706,0.382353,534.470588,0.176471,343.852941,30.970588,3.382353,...,94.764706,76.867647,55.500000,66.970588,82.500000,38.779412,63.573529,-0.129706,-0.129706,21879.264706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nia+456@rowan.kr,1.542480,573.781250,2676.125000,10846.750000,5.421875,610.515625,0.609375,283.140625,64.000000,40.562500,...,88.718750,85.031250,57.468750,42.156250,83.828125,31.234375,51.750000,-0.125469,-0.125469,18961.875000
nia+458@rowan.kr,1.257353,200.549020,2206.941176,3377.098039,0.588235,507.117647,0.392157,206.823529,9.176471,4.333333,...,90.686275,88.882353,72.745098,67.705882,75.529412,82.607843,85.274510,-0.040000,-0.040000,28078.823529
nia+462@rowan.kr,1.595274,654.780488,2748.975610,12247.487805,3.121951,473.658537,0.560976,309.951220,84.804878,22.536585,...,90.073171,99.634146,71.121951,63.146341,85.317073,28.951220,68.634146,-0.037317,-0.037317,23045.121951
nia+475@rowan.kr,1.397418,311.869565,2410.043478,5543.195652,0.108696,675.282609,1.130435,278.891304,23.347826,0.782609,...,57.130435,94.456522,68.130435,80.413043,85.913043,27.586957,54.695652,-0.159348,-0.159348,19752.391304
nia+85@rowan.kr,1.336538,290.494505,2327.934066,5319.571429,0.274725,551.516484,0.538462,228.934066,24.351648,1.989011,...,87.626374,95.340659,76.604396,78.186813,82.230769,37.230769,63.285714,-0.008681,-0.008681,21857.142857

In [22]:
activity_sleep.isnull().any().any() # no null values.

False

In [23]:
label_data.rename(columns={"SAMPLE_EMAIL":"EMAIL"}, inplace=True)

In [24]:
activity_sleep_label = pd.merge(activity_sleep,label_data, how='outer',on='EMAIL')
activity_sleep_label

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_high,activity_inactive,activity_inactivity_alerts,activity_low,activity_medium,...,sleep_score_deep,sleep_score_disturbances,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,DIAG_NM
0,nia+003@rowan.kr,1.262897,202.571429,2208.333333,3659.730159,0.793651,615.142857,0.809524,146.428571,18.333333,...,75.492063,57.634921,65.253968,78.650794,54.904762,69.730159,0.022222,0.022222,23543.809524,MCI
1,nia+005@rowan.kr,1.370299,217.477876,1773.504425,5084.876106,0.256637,574.619469,0.539823,281.300885,15.398230,...,89.345133,83.601770,97.663717,83.973451,74.433628,81.097345,0.057434,0.057434,28060.088496,CN
2,nia+010@rowan.kr,1.390625,259.672414,2365.137931,3877.741379,0.637931,632.482759,0.362069,328.827586,9.068966,...,61.517241,63.758621,58.034483,76.965517,64.672414,58.344828,-0.045862,-0.045862,20247.413793,MCI
3,nia+013@rowan.kr,1.478484,493.147541,2577.590164,8769.811475,0.836066,481.016393,0.745902,314.918033,48.426230,...,97.606557,72.549180,88.073770,81.721311,36.295082,69.049180,0.008033,0.008033,23163.196721,MCI
4,nia+014@rowan.kr,1.442555,401.382353,2503.882353,7250.514706,0.382353,534.470588,0.176471,343.852941,30.970588,...,76.867647,55.500000,66.970588,82.500000,38.779412,63.573529,-0.129706,-0.129706,21879.264706,MCI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,nia+456@rowan.kr,1.542480,573.781250,2676.125000,10846.750000,5.421875,610.515625,0.609375,283.140625,64.000000,...,85.031250,57.468750,42.156250,83.828125,31.234375,51.750000,-0.125469,-0.125469,18961.875000,CN
170,nia+458@rowan.kr,1.257353,200.549020,2206.941176,3377.098039,0.588235,507.117647,0.392157,206.823529,9.176471,...,88.882353,72.745098,67.705882,75.529412,82.607843,85.274510,-0.040000,-0.040000,28078.823529,CN
171,nia+462@rowan.kr,1.595274,654.780488,2748.975610,12247.487805,3.121951,473.658537,0.560976,309.951220,84.804878,...,99.634146,71.121951,63.146341,85.317073,28.951220,68.634146,-0.037317,-0.037317,23045.121951,MCI
172,nia+475@rowan.kr,1.397418,311.869565,2410.043478,5543.195652,0.108696,675.282609,1.130435,278.891304,23.347826,...,94.456522,68.130435,80.413043,85.913043,27.586957,54.695652,-0.159348,-0.159348,19752.391304,CN
173,nia+85@rowan.kr,1.336538,290.494505,2327.934066,5319.571429,0.274725,551.516484,0.538462,228.934066,24.351648,...,95.340659,76.604396,78.186813,82.230769,37.230769,63.285714,-0.008681,-0.008681,21857.142857,CN

In [25]:
activity_sleep_label.columns

Index(['EMAIL', 'activity_average_met', 'activity_cal_active',
       'activity_cal_total', 'activity_daily_movement', 'activity_high',
       'activity_inactive', 'activity_inactivity_alerts', 'activity_low',
       'activity_medium', 'activity_met_min_high', 'activity_met_min_inactive',
       'activity_met_min_low', 'activity_met_min_medium', 'activity_non_wear',
       'activity_rest', 'activity_score', 'activity_score_meet_daily_targets',
       'activity_score_move_every_hour', 'activity_score_recovery_time',
       'activity_score_stay_active', 'activity_score_training_frequency',
       'activity_score_training_volume', 'activity_steps', 'activity_total',
       'sleep_awake', 'sleep_breath_average', 'sleep_deep', 'sleep_duration',
       'sleep_efficiency', 'sleep_hr_average', 'sleep_hr_lowest',
       'sleep_is_longest', 'sleep_light', 'sleep_midpoint_at_delta',
       'sleep_midpoint_time', 'sleep_onset_latency', 'sleep_period_id',
       'sleep_rem', 'sleep_restless', 'sleep_rmssd', 'sleep_score',
       'sleep_score_alignment', 'sleep_score_deep', 'sleep_score_disturbances',
       'sleep_score_efficiency', 'sleep_score_latency', 'sleep_score_rem',
       'sleep_score_total', 'sleep_temperature_delta',
       'sleep_temperature_deviation', 'sleep_total', 'DIAG_NM'],
      dtype='object')

In [26]:
# change the order of columns
activity_sleep_label = activity_sleep_label[['EMAIL', 'DIAG_NM', 'activity_average_met', 'activity_cal_active',
       'activity_cal_total', 'activity_daily_movement', 'activity_high',
       'activity_inactive', 'activity_inactivity_alerts', 'activity_low',
       'activity_medium', 'activity_met_min_high', 'activity_met_min_inactive',
       'activity_met_min_low', 'activity_met_min_medium', 'activity_non_wear',
       'activity_rest', 'activity_score', 'activity_score_meet_daily_targets',
       'activity_score_move_every_hour', 'activity_score_recovery_time',
       'activity_score_stay_active', 'activity_score_training_frequency',
       'activity_score_training_volume', 'activity_steps', 'activity_total',
       'sleep_awake', 'sleep_breath_average', 'sleep_deep', 'sleep_duration',
       'sleep_efficiency', 'sleep_hr_average', 'sleep_hr_lowest',
       'sleep_is_longest', 'sleep_light', 'sleep_midpoint_at_delta',
       'sleep_midpoint_time', 'sleep_onset_latency', 'sleep_period_id',
       'sleep_rem', 'sleep_restless', 'sleep_rmssd', 'sleep_score',
       'sleep_score_alignment', 'sleep_score_deep', 'sleep_score_disturbances',
       'sleep_score_efficiency', 'sleep_score_latency', 'sleep_score_rem',
       'sleep_score_total', 'sleep_temperature_delta',
       'sleep_temperature_deviation', 'sleep_total']]
activity_sleep_label

,EMAIL,DIAG_NM,activity_average_met,activity_cal_active,activity_cal_total,activity_daily_movement,activity_high,activity_inactive,activity_inactivity_alerts,activity_low,...,sleep_score_alignment,sleep_score_deep,sleep_score_disturbances,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total
0,nia+003@rowan.kr,MCI,1.262897,202.571429,2208.333333,3659.730159,0.793651,615.142857,0.809524,146.428571,...,74.809524,75.492063,57.634921,65.253968,78.650794,54.904762,69.730159,0.022222,0.022222,23543.809524
1,nia+005@rowan.kr,CN,1.370299,217.477876,1773.504425,5084.876106,0.256637,574.619469,0.539823,281.300885,...,86.849558,89.345133,83.601770,97.663717,83.973451,74.433628,81.097345,0.057434,0.057434,28060.088496
2,nia+010@rowan.kr,MCI,1.390625,259.672414,2365.137931,3877.741379,0.637931,632.482759,0.362069,328.827586,...,97.931034,61.517241,63.758621,58.034483,76.965517,64.672414,58.344828,-0.045862,-0.045862,20247.413793
3,nia+013@rowan.kr,MCI,1.478484,493.147541,2577.590164,8769.811475,0.836066,481.016393,0.745902,314.918033,...,90.139344,97.606557,72.549180,88.073770,81.721311,36.295082,69.049180,0.008033,0.008033,23163.196721
4,nia+014@rowan.kr,MCI,1.442555,401.382353,2503.882353,7250.514706,0.382353,534.470588,0.176471,343.852941,...,94.764706,76.867647,55.500000,66.970588,82.500000,38.779412,63.573529,-0.129706,-0.129706,21879.264706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,nia+456@rowan.kr,CN,1.542480,573.781250,2676.125000,10846.750000,5.421875,610.515625,0.609375,283.140625,...,88.718750,85.031250,57.468750,42.156250,83.828125,31.234375,51.750000,-0.125469,-0.125469,18961.875000
170,nia+458@rowan.kr,CN,1.257353,200.549020,2206.941176,3377.098039,0.588235,507.117647,0.392157,206.823529,...,90.686275,88.882353,72.745098,67.705882,75.529412,82.607843,85.274510,-0.040000,-0.040000,28078.823529
171,nia+462@rowan.kr,MCI,1.595274,654.780488,2748.975610,12247.487805,3.121951,473.658537,0.560976,309.951220,...,90.073171,99.634146,71.121951,63.146341,85.317073,28.951220,68.634146,-0.037317,-0.037317,23045.121951
172,nia+475@rowan.kr,CN,1.397418,311.869565,2410.043478,5543.195652,0.108696,675.282609,1.130435,278.891304,...,57.130435,94.456522,68.130435,80.413043,85.913043,27.586957,54.695652,-0.159348,-0.159348,19752.391304
173,nia+85@rowan.kr,CN,1.336538,290.494505,2327.934066,5319.571429,0.274725,551.516484,0.538462,228.934066,...,87.626374,95.340659,76.604396,78.186813,82.230769,37.230769,63.285714,-0.008681,-0.008681,21857.142857

In [27]:
# save as csv file
activity_sleep_label.to_csv("./activity_sleep_label.csv")