In [1]:
import pandas as pd

In [5]:
training_label = pd.read_csv("./128.치매 고위험군 라이프로그/01.데이터/1.Training/라벨링데이터/1.걸음걸이/training_label.csv")
training_label

         SAMPLE_EMAIL DIAG_NM
0    nia+315@rowan.kr      CN
1    nia+014@rowan.kr     MCI
2    nia+220@rowan.kr      CN
3    nia+096@rowan.kr     MCI
4    nia+396@rowan.kr      CN
..                ...     ...
136  nia+181@rowan.kr      CN
137  nia+354@rowan.kr      CN
138  nia+448@rowan.kr     MCI
139  nia+394@rowan.kr      CN
140  nia+067@rowan.kr     Dem

[141 rows x 2 columns]

In [9]:
train_activity = pd.read_csv("./128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/1.걸음걸이/train_activity.csv")
train_activity

,EMAIL,activity_average_met,activity_cal_active,activity_cal_total,activity_class_5min,activity_daily_movement,activity_day_end,activity_day_start,activity_high,activity_inactive,...,activity_score_meet_daily_targets,activity_score_move_every_hour,activity_score_recovery_time,activity_score_stay_active,activity_score_training_frequency,activity_score_training_volume,activity_steps,activity_total,CONVERT(activity_class_5min USING utf8),CONVERT(activity_met_1min USING utf8)
0,nia+279@rowan.kr,1.28125,196,2251,...,3353,2020-10-20T03:59:59+09:00,2020-10-19T04:00:00+09:00,0,714,...,78,100,100,54,100,97,4212,207,1/1/2/2/2/2/1/1/1/1/1/1/1/2/2/2/2/2/2/3/3/2/2/...,1.2/0.9/1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/...
1,nia+279@rowan.kr,1.25000,145,2159,...,2516,2020-10-21T03:59:59+09:00,2020-10-20T04:00:00+09:00,0,719,...,60,100,100,58,96,96,3306,140,1/1/1/2/2/2/2/2/2/2/2/2/1/1/1/1/1/2/3/3/3/3/2/...,0.9/0.9/1.3/1/0.9/0.9/1.1/0.9/1/0.9/1/0.9/1/0....
2,nia+279@rowan.kr,1.21875,118,2140,...,1716,2020-10-22T03:59:59+09:00,2020-10-21T04:00:00+09:00,0,708,...,43,95,100,55,71,83,2550,131,1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/2/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
3,nia+279@rowan.kr,1.28125,180,2240,...,2791,2020-10-23T03:59:59+09:00,2020-10-22T04:00:00+09:00,0,705,...,43,100,100,58,71,59,4009,208,1/1/1/1/1/1/1/1/1/1/2/2/2/2/3/3/3/2/3/3/3/3/3/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
4,nia+279@rowan.kr,1.46875,374,2559,...,5393,2020-10-24T03:59:59+09:00,2020-10-23T04:00:00+09:00,0,437,...,43,100,100,89,40,46,8081,517,1/1/1/2/2/2/2/2/2/1/1/1/3/2/2/1/2/2/2/3/3/2/2/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,1.34375,249,2351,...,4411,2020-12-25T03:59:59+09:00,2020-12-24T04:00:00+09:00,1,780,...,25,43,100,45,40,95,4972,190,1/1/1/1/1/1/1/1/1/1/2/3/2/2/2/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
9701,nia+206@rowan.kr,1.53125,570,2682,...,11057,2020-12-27T03:59:59+09:00,2020-12-26T04:00:00+09:00,1,518,...,43,95,100,76,71,93,11878,394,1/1/1/1/1/1/2/2/2/2/2/2/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/1.1/0.9/0.9/1.1/0.9/0.9/0.9/0....
9702,nia+206@rowan.kr,1.34375,295,2331,...,5135,2020-12-28T03:59:59+09:00,2020-12-27T04:00:00+09:00,4,578,...,25,100,100,70,40,95,5752,207,1/1/1/2/3/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,1.1/0.9/0.9/0.9/1/0.9/0.9/0.9/0.9/0.9/0.9/0.9/...
9703,nia+206@rowan.kr,1.31250,186,2280,...,3178,2020-12-29T03:59:59+09:00,2020-12-28T04:00:00+09:00,0,778,...,25,95,100,47,40,93,3852,156,1/1/1/1/1/1/1/1/1/1/1/1/2/2/0/0/0/0/0/0/0/0/0/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....
9704,nia+206@rowan.kr,1.37500,83,1891,...,1554,2020-12-30T03:59:59+09:00,2020-12-29T04:00:00+09:00,0,69,...,25,100,100,48,40,82,1500,68,1/1/1/1/2/2/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/1/...,0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0.9/0....

In [8]:
train_sleep = pd.read_csv("./128.치매 고위험군 라이프로그/01.데이터/1.Training/원천데이터/2.수면/train_sleep.csv")
train_sleep

,EMAIL,sleep_awake,sleep_bedtime_end,sleep_bedtime_start,sleep_breath_average,sleep_deep,sleep_duration,sleep_efficiency,sleep_hr_5min,sleep_hr_average,...,sleep_score_efficiency,sleep_score_latency,sleep_score_rem,sleep_score_total,sleep_temperature_delta,sleep_temperature_deviation,sleep_total,CONVERT(sleep_hr_5min USING utf8),CONVERT(sleep_hypnogram_5min USING utf8),CONVERT(sleep_rmssd_5min USING utf8)
0,nia+279@rowan.kr,8700,2020-10-19T05:10:28+09:00,2020-10-18T18:38:28+09:00,17.875,10110,37920,77,...,53.04,...,65,89,56,94,0.00,0.00,29220,63/61/59/58/58/58/56/55/54/53/53/53/0/0/54/57/...,4/2/2/2/2/1/1/2/2/2/2/2/4/4/4/1/1/4/4/4/2/2/2/...,18/28/25/28/34/34/35/45/54/36/36/60/0/0/34/22/...
1,nia+279@rowan.kr,6570,2020-10-20T05:37:52+09:00,2020-10-19T21:39:52+09:00,18.000,7440,28680,77,...,52.82,...,65,97,43,65,0.34,0.34,22110,0/51/0/51/52/52/52/52/53/53/53/52/52/53/53/53/...,4/2/4/2/2/2/1/1/1/2/2/3/3/3/3/3/3/3/1/1/1/4/4/...,0/49/0/38/51/17/18/18/26/27/24/29/36/31/32/34/...
2,nia+279@rowan.kr,10530,2020-10-21T05:45:28+09:00,2020-10-20T20:51:28+09:00,18.000,4620,32040,67,...,52.01,...,41,75,68,62,-0.07,-0.07,21510,54/56/0/55/53/55/56/55/0/55/54/54/54/0/0/55/55...,4/2/1/1/2/2/4/4/4/4/2/2/2/4/4/4/2/4/4/4/4/4/4/...,56/47/0/49/42/57/44/49/0/46/54/47/55/0/0/55/53...
3,nia+279@rowan.kr,4080,2020-10-22T05:12:16+09:00,2020-10-21T22:08:16+09:00,17.500,7440,25440,84,...,51.07,...,81,83,73,62,-0.14,-0.14,21360,0/54/53/53/54/54/54/53/53/53/53/54/51/50/51/51...,4/4/1/1/1/1/1/1/1/1/1/4/2/2/2/2/1/1/1/1/1/4/2/...,0/40/40/40/37/46/35/46/44/56/50/48/41/55/55/50...
4,nia+279@rowan.kr,7170,2020-10-23T02:23:30+09:00,2020-10-22T20:38:30+09:00,17.875,4320,20700,65,...,50.80,...,39,78,25,29,-0.50,-0.50,13530,0/49/50/50/50/50/50/50/51/0/0/0/0/0/0/0/0/50/5...,4/2/2/2/2/1/1/1/2/4/4/4/4/4/4/4/4/4/2/1/1/1/1/...,0/81/60/74/62/63/56/78/81/0/0/0/0/0/0/0/0/60/4...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9700,nia+206@rowan.kr,6000,2020-12-24T06:51:37+09:00,2020-12-23T21:35:37+09:00,15.875,1710,33360,82,...,63.75,...,76,81,95,86,-0.09,-0.09,27360,68/66/67/67/68/69/69/70/71/71/71/69/72/70/70/7...,4/4/2/2/2/1/1/1/1/1/1/2/2/3/3/2/2/2/2/2/3/4/2/...,26/16/19/18/16/18/19/17/15/16/15/13/11/13/13/1...
9701,nia+206@rowan.kr,5700,2020-12-26T06:36:19+09:00,2020-12-25T22:54:19+09:00,16.125,0,27720,79,...,67.40,...,69,86,89,64,0.41,0.41,22020,0/0/65/65/66/67/69/72/73/72/73/74/73/74/75/75/...,4/4/2/2/2/2/2/2/2/2/2/2/4/4/4/4/2/3/3/3/2/2/4/...,0/0/13/12/12/13/12/12/12/16/13/12/13/17/13/18/...
9702,nia+206@rowan.kr,5070,2020-12-27T07:56:40+09:00,2020-12-26T22:05:40+09:00,15.625,480,35460,86,...,64.84,...,86,89,98,97,0.27,0.27,30390,0/0/0/64/64/64/64/65/65/66/66/66/66/68/68/68/6...,4/4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/2/4/4/2/2/2/...,0/0/0/14/17/18/14/14/17/15/17/12/17/12/13/12/1...
9703,nia+206@rowan.kr,2040,2020-12-28T05:05:45+09:00,2020-12-27T21:21:45+09:00,15.875,2220,27840,93,...,67.05,...,98,89,86,80,-0.05,-0.05,25800,0/60/60/61/60/60/60/62/64/64/64/64/65/68/70/70...,4/4/1/2/2/2/2/1/2/2/2/1/1/1/3/3/1/1/2/2/3/3/3/...,0/14/15/14/15/16/17/16/16/18/18/20/23/15/21/20...
9704,nia+206@rowan.kr,3390,2020-12-29T06:10:26+09:00,2020-12-28T22:59:26+09:00,16.625,600,25860,87,...,62.49,...,88,99,76,66,0.26,0.26,22470,0/0/0/62/62/62/61/60/60/61/61/62/0/67/66/66/66...,4/4/4/2/2/2/2/2/2/2/2/2/3/3/3/3/3/2/2/2/2/2/2/...,0/0/0/19/18/22/20/16/16/16/14/18/0/36/28/23/21...

In [12]:
len(train_activity.EMAIL.unique())

141